export { ReactComponent as HistoryIcon } from './history.svg'
export { ReactComponent as ExchangeIcon } from './money-exchange.svg'
export { ReactComponent as LogoIcon } from './shazam.svg'
export { ReactComponent as TransferIcon } from './transfer.svg'
export { ReactComponent as AccountIcon } from './user.svg'
export { ReactComponent as WalletIcon } from './wallet-filled-money-tool.svg'
export { ReactComponent as NotFoundIcon } from './error-404.svg'
